apiVersion: apps/v1
kind: Deployment
metadata:
  name: dx-360-germany
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dx-360-germany
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: dx-360-germany
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: dx-360-germany
        image: crkmdevweu.azurecr.io/dx360:v1
        command: ["bash","-c","cd /var/www/html/ && apache2-foreground"]
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 1
          limits:
            cpu: 2
        env:
        - name: DB_NAME
          value: "drupal"
        - name: DB_USER
          value: "KMuser@km-dev-mysql-server"
        - name: DB_PASS
          value: "Admin@1234"
        - name: DB_HOST
          value: "km-dev-mysql-server.mysql.database.azure.com"
        - name: DB_PORT
          value: "3306"
        - name: KM_ENV
          value: "DEV"
        - name: SOLR_HOST
          value: "51.140.60.44"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-dx-360-germany
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dx-360-germany
