apiVersion: apps/v1
kind: Deployment
metadata:
  name: dx-360-germany-dev-tls
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dx-360-germany-dev-tls
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: dx-360-germany-dev-tls
    spec:
      containers:
      - name: dx-360-germany-dev-tls
        image: crkmdeveuw.azurecr.io/dx-360-germany-dev-tls:v1
        command: ["bash","-c","cd /var/www/html/ && apache2-foreground"]
        ports:
        - containerPort: 443
        env:
        - name: DB_NAME
          value: "dev360_germany"
        - name: DB_USER
          value: "devadmin@mysql007"
        - name: DB_PASS
          value: "Admin@123"
        - name: DB_HOST
          value: "mysql007.mysql.database.azure.com"
        - name: DB_PORT
          value: "3306"
        resources:
          requests:
            cpu: "1"
          limits:
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-dx-360-germany-dev-tls
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 443
  selector:
    app: dx-360-germany-dev-tls
