apiVersion: apps/v1
kind: Deployment
metadata:
  name: dx-360-austria-dev
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dx-360-austria-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: dx-360-austria-dev
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: dx-360-austria-dev
        image: crkmdeveuw.azurecr.io/dx-360-austria-dev-notls:v1
        command: ["bash","-c","cd /var/www/html/ && apache2-foreground"]
        ports:
        - containerPort: 80
        env:
        - name: DB_NAME
          value: "devaustria"
        - name: DB_USER
          value: "devadmin@mysql007"
        - name: DB_PASS
          value: "Admin@123"
        - name: DB_HOST
          value: "mysql007.mysql.database.azure.com"
        - name: DB_PORT
          value: "3306"
        resources:
          requests:
            cpu: "1"
          limits:
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-dx-360-austria-dev
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: dx-360-austria-dev
